# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 03:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naem', models.CharField(max_length=128, unique=True)),
                ('interest_manage_rate', models.FloatField()),
                ('pick_up_rate', models.FloatField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AccountRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('apply_type', models.CharField(max_length=128)),
                ('year_rate', models.FloatField(default=0)),
                ('days', models.IntegerField(null=True)),
                ('months', models.IntegerField(null=True)),
                ('quarters', models.IntegerField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.Account')),
            ],
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField()),
                ('date', models.DateField()),
                ('account_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.AccountRecord')),
            ],
        ),
    ]
