# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='interest_manage_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='account',
            name='pick_up_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
