# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_auto_20160313_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='naem',
            new_name='name',
        ),
    ]
