# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 12:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial', '0003_auto_20160313_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('interest_manage_rate', models.FloatField(default=0.0)),
                ('pick_up_rate', models.FloatField(default=0.0)),
                ('comment', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
