# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_auto_20160319_2130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
