# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0007_auto_20160320_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrecord',
            name='comment',
            field=models.CharField(default='', max_length=128),
        ),
    ]
