# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0008_accountrecord_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountrecord',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
