# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecondHandHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_link', models.URLField(default='', unique=True)),
                ('title', models.CharField(max_length=1024)),
                ('sub_title', models.CharField(max_length=1024)),
                ('total_price', models.IntegerField(default=0)),
                ('unit_price', models.IntegerField(default=0)),
                ('first_price', models.IntegerField(default=0)),
                ('last_collect_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
