# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lianjia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondhandhouse',
            name='like_rate',
            field=models.IntegerField(default=3),
        ),
    ]
