# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lianjia', '0004_auto_20170222_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondhandhouse',
            name='pictures',
            field=models.IntegerField(default=1),
        ),
    ]
