# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lianjia', '0005_secondhandhouse_pictures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondhandhouse',
            name='pictures',
        ),
        migrations.AddField(
            model_name='secondhandhouse',
            name='has_pictures',
            field=models.BooleanField(default=True),
        ),
    ]
