# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lianjia', '0006_auto_20170222_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondhandhouse',
            name='for_sell',
            field=models.BooleanField(default=True),
        ),
    ]
