# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lianjia', '0007_secondhandhouse_for_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondhandhouse',
            name='rooms_number',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
