# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lianjia', '0012_auto_20170224_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondhandhouse',
            name='listing_time',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='secondhandhouse',
            name='remarks',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
