# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('duration', models.IntegerField(default=0)),
                ('year_rate', models.FloatField(default=0)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Platform'),
        ),
    ]
