# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20160330_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='available_money',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='total_money',
            field=models.FloatField(default=0),
        ),
    ]
