# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_loan_for_new_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='last_update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
