# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_platform_last_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='link',
            field=models.URLField(default=''),
        ),
    ]
